[build-system]
requires = ["setuptools>=74.1"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-cubing"
version = "0.1.0"
description = "MCP server for Rubik's cube manipulation and visualization"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.1.0",
    "cubing-algs>=1.0.14",
    "kociemba==1.2.1",
]
keywords = ["mcp", "rubick", "cube", "speedcubing", "solve", "algorithm"]
authors = [{name = "Fantomas42", email = "fantomas42@gmail.com"}]
classifiers = [
  "Programming Language :: Python"
]

[project.urls]
repository = "https://github.com/Fantomas42/mcp-cubing"

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-subtests",
]

[tool.ruff.lint]
preview = true
fixable = ["ALL"]
select = ["ALL"]
ignore = [
    "PT009",
    "CPY001",
    "D203",
    "D205",
    "D212",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ruff]
line-length = 80
indent-width = 4
target-version = "py312"
show-fixes = true

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.isort]
force-single-line = true

[tool.pytest.ini_options]
addopts = "--cov=src/mcp_cubing"

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
