name: Kwalitee
permissions:
  contents: read

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]


jobs:
  Kwalitee:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Analysing the code with Mypy
      run: |
        mypy src --strict
      continue-on-error: true
    - name: Analysing the code with Ruff
      run: |
        ruff check $(git ls-files 'src/mcp_cubing/*.py')
      continue-on-error: true
